# Trackers test

This notebook demonstrates tests the trackers in flax-pilot against tf.keras

**Use TensorFlow-cpu instead of TensorFlow to avoid any issues between TensorFlow & Jax.**

In [ ]:
!pip install -q tensorflow-cpu

In [7]:
import jax
import tensorflow as tf
import flax.linen as nn
import jax.numpy as jnp
import jax.random as jr

In [8]:
import sys
sys.path.append("/kaggle/input/flax-trainer")

In [9]:
import trackers as tr

### Binary Classification Accuracy and MultiLabel Accuracy Trackers

In [175]:
tf_binary = tf.keras.metrics.BinaryAccuracy(threshold=0.7)
fp_binary = tr.BinaryAccuracy(threshold=0.7)

#### Binary

In [156]:
for i in range(50):
    true = tf.random.uniform((32, 1), minval=0, maxval=2, dtype=tf.int32).numpy()
    pred = tf.random.uniform((32, 1), minval=0, maxval=2, dtype=tf.int32).numpy()
    fp_binary.update(true, pred)
    tf_binary.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_binary.compute())
        print("TF result: ",tf_binary.result().numpy())
        tf_binary.reset_state()
        fp_binary.reset()

Result
FP result:  0.49999994
TF result:  0.5
Result
FP result:  0.53125
TF result:  0.53125
Result
FP result:  0.484375
TF result:  0.484375
Result
FP result:  0.53125
TF result:  0.53125
Result
FP result:  0.50625
TF result:  0.50625


#### MultiLabel

In [176]:
for i in range(50):
    true = tf.random.uniform((32, 10), minval=0, maxval=2, dtype=tf.int32).numpy()
    pred = tf.random.uniform((32, 10), minval=0, maxval=2, dtype=tf.int32).numpy()
    fp_binary.update(true, pred)
    tf_binary.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_binary.compute())
        print("TF result: ",tf_binary.result().numpy())
        tf_binary.reset_state()
        fp_binary.reset()

Result
FP result:  0.5093749
TF result:  0.50937504
Result
FP result:  0.5134375
TF result:  0.51343757
Result
FP result:  0.5046875
TF result:  0.5046875
Result
FP result:  0.49999997
TF result:  0.49999994
Result
FP result:  0.515625
TF result:  0.515625


### Multiclass Accuracy Trackers

In [157]:
tf_mc = tf.keras.metrics.CategoricalAccuracy()
fp_mc = tr.Accuracy()

In [158]:
for i in range(50):
    true = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    pred = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    fp_mc.update(true, pred)
    tf_mc.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_mc.compute())
        print("TF result: ",tf_mc.result().numpy())
        tf_mc.reset_state()
        fp_mc.reset()

Result
FP result:  0.031249996
TF result:  0.03125
Result
FP result:  0.10625
TF result:  0.10625
Result
FP result:  0.112500004
TF result:  0.1125
Result
FP result:  0.0875
TF result:  0.0875
Result
FP result:  0.081250004
TF result:  0.08125


### Common Classification trackers

#### f1 macro

In [201]:
tf_f1 = tf.keras.metrics.F1Score(threshold=0.5, average='macro')
fp_f1 = tr.F1Score(num_classes=10, threshold=0.5, average='macro')

for i in range(50):
    true = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    pred = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    
    fp_f1.update(true, pred)
    tf_f1.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_f1.compute())
        print("TF result: ",tf_f1.result().numpy())
        tf_f1.reset_state()
        fp_f1.reset()

Result
FP result:  0.18285713
TF result:  0.18285713
Result
FP result:  0.09174189
TF result:  0.0917419
Result
FP result:  0.12526697
TF result:  0.12526695
Result
FP result:  0.097157255
TF result:  0.097157255
Result
FP result:  0.09537021
TF result:  0.0953702


In [202]:
tf_f1.true_positives.value, tf_f1.false_positives.value, tf_f1.false_negatives.value

(<tf.Variable 'f1_score/true_positives:0' shape=(10,) dtype=float32, numpy=array([3., 4., 4., 5., 2., 4., 1., 5., 3., 5.], dtype=float32)>,
 <tf.Variable 'f1_score/false_positives:0' shape=(10,) dtype=float32, numpy=array([25., 25., 23., 27., 23., 24., 33., 21., 27., 24.], dtype=float32)>,
 <tf.Variable 'f1_score/false_negatives:0' shape=(10,) dtype=float32, numpy=array([19., 25., 18., 39., 26., 30., 29., 24., 25., 17.], dtype=float32)>)

In [203]:
fp_f1.tp , fp_f1.fp, fp_f1.fn

(Array([3., 4., 4., 5., 2., 4., 1., 5., 3., 5.], dtype=float32),
 Array([25., 25., 23., 27., 23., 24., 33., 21., 27., 24.], dtype=float32),
 Array([19., 25., 18., 39., 26., 30., 29., 24., 25., 17.], dtype=float32))

#### f1 micro

In [204]:
tf_f1 = tf.keras.metrics.F1Score(threshold=0.5, average='micro')
fp_f1 = tr.F1Score(num_classes=10, threshold=0.5, average='micro')

for i in range(50):
    true = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    pred = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    fp_f1.update(true, pred)
    tf_f1.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_f1.compute())
        print("TF result: ",tf_f1.result().numpy())
        tf_f1.reset_state()
        fp_f1.reset()

Result
FP result:  0.124999955
TF result:  0.124999955
Result
FP result:  0.13437496
TF result:  0.13437496
Result
FP result:  0.09687495
TF result:  0.096874945
Result
FP result:  0.10624995
TF result:  0.10624995
Result
FP result:  0.07812495
TF result:  0.07812495


In [205]:
tf_f1.true_positives.value, tf_f1.false_positives.value, tf_f1.false_negatives.value

(<tf.Variable 'f1_score/true_positives:0' shape=() dtype=float32, numpy=41.0>,
 <tf.Variable 'f1_score/false_positives:0' shape=() dtype=float32, numpy=247.0>,
 <tf.Variable 'f1_score/false_negatives:0' shape=() dtype=float32, numpy=247.0>)

In [206]:
fp_f1.tp , fp_f1.fp, fp_f1.fn

(Array(41., dtype=float32),
 Array(247., dtype=float32),
 Array(247., dtype=float32))

#### precision 

In [207]:
tf_p = tf.keras.metrics.Precision()
fp_p = tr.Precision(num_classes=10, threshold=0.5, average='micro')

for i in range(50):
    true = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    pred = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    fp_p.update(true, pred)
    tf_p.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_p.compute())
        print("TF result: ",tf_p.result().numpy())
        tf_p.reset_state()
        fp_p.reset()

Result
FP result:  0.0625
TF result:  0.0625
Result
FP result:  0.084375
TF result:  0.084375
Result
FP result:  0.128125
TF result:  0.128125
Result
FP result:  0.109375
TF result:  0.109375
Result
FP result:  0.134375
TF result:  0.134375


#### recall

In [208]:
tf_r = tf.keras.metrics.Recall()
fp_r = tr.Recall(num_classes=10, threshold=0.5, average='micro')

for i in range(50):
    true = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    pred = tf.one_hot(tf.random.uniform((32, ), minval=0, maxval=10, dtype=tf.int32), 10).numpy()
    fp_r.update(true, pred)
    tf_r.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_r.compute())
        print("TF result: ",tf_r.result().numpy())
        tf_r.reset_state()
        fp_r.reset()

Result
FP result:  0.03125
TF result:  0.03125
Result
FP result:  0.0875
TF result:  0.0875
Result
FP result:  0.081250004
TF result:  0.08125
Result
FP result:  0.1
TF result:  0.1
Result
FP result:  0.090625
TF result:  0.090625


### Mean

In [209]:
tf_mean = tf.keras.metrics.Mean()
fp_mean = tr.Mean()

for i in range(50):
    val = tf.random.uniform((32, 128), minval=1, maxval=2).numpy().mean()
    fp_mean.update(val)
    tf_mean.update_state(val)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_mean.compute())
        print("TF result: ",tf_mean.result().numpy())
        tf_mean.reset_state()
        fp_mean.reset()

Result
FP result:  1.498339
TF result:  1.4983392
Result
FP result:  1.4995415
TF result:  1.4995415
Result
FP result:  1.501404
TF result:  1.501404
Result
FP result:  1.5013682
TF result:  1.5013682
Result
FP result:  1.5002176
TF result:  1.5002176


### MSE

In [210]:
tf_mse = tf.keras.metrics.MeanSquaredError()
fp_mse = tr.MSE()

for i in range(50):
    true = tf.random.normal((32, 128)).numpy()
    pred = tf.random.normal((32, 128)).numpy()
    fp_mse.update(true, pred)
    tf_mse.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_mse.compute())
        print("TF result: ",tf_mse.result().numpy())
        tf_mse.reset_state()
        fp_mse.reset()

Result
FP result:  2.0105805
TF result:  2.0105808
Result
FP result:  2.0115135
TF result:  2.0115135
Result
FP result:  1.9925972
TF result:  1.9925972
Result
FP result:  1.9945897
TF result:  1.9945896
Result
FP result:  2.0256476
TF result:  2.0256476


### MAE

In [211]:
tf_mae = tf.keras.metrics.MeanAbsoluteError()
fp_mae = tr.MAE()

for i in range(50):
    true = tf.random.normal((32, 128)).numpy()
    pred = tf.random.normal((32, 128)).numpy()
    fp_mae.update(true, pred)
    tf_mae.update_state(true, pred)
    if i%10==0:
        print("Result")
        print("FP result: ",fp_mae.compute())
        print("TF result: ",tf_mae.result().numpy())
        tf_mae.reset_state()
        fp_mae.reset()

Result
FP result:  1.1047202
TF result:  1.1047204
Result
FP result:  1.1208715
TF result:  1.1208715
Result
FP result:  1.1314877
TF result:  1.1314876
Result
FP result:  1.1328486
TF result:  1.1328485
Result
FP result:  1.1345313
TF result:  1.1345313
